server:
  port: 9090

spring:
  main:
    allow-circular-references: on
  datasource:
    password: Kiran571
    url: jdbc:mysql://localhost:3306/jwt
    username: root
  jpa:
    hibernate:
      ddl-auto: create


